apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-api
  namespace: library-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-api
  template:
    metadata:
      labels:
        app: library-api
    spec:
      containers:
        - name: library-api
          image: furkandurceylan/library-api:20
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/postgres?currentSchema=library

            - name: SPRING_DATASOURCE_USERNAME
              value: postgres

            - name: SPRING_DATASOURCE_PASSWORD
              value: admin

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: library-security
                  key: JWT_SECRET

            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: library-security
                  key: JWT_EXPIRATION

            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: library-security
                  key: ADMIN_EMAIL

            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: library-security
                  key: ADMIN_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: library-api
  namespace: library-prod
spec:
  selector:
    app: library-api
  ports:
    - port: 8080
      targetPort: 8080


