spring.application.name=LibApi
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=library
spring.datasource.username=postgres
spring.datasource.password=admin


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security & JWT Configuration
jwt.secret=${JWT_SECRET:c3VwZXJTZWNyZXRLZXlGb3JMaWJyYXJ5QXBpSnd0QXV0aGVudGljYXRpb25TeXN0ZW1XaXRoMjU2Qml0cw==}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Initial Admin Seeding Configuration
admin.email=${ADMIN_EMAIL:admin@test.com}
admin.password=${ADMIN_PASSWORD:password}
