apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-api
  namespace: library-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-api
  template:
    metadata:
      labels:
        app: library-api
    spec:
      containers:
        - name: library-api
          image: furkandurceylan/library-api:20
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/postgres?currentSchema=library
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin

---
apiVersion: v1
kind: Service
metadata:
  name: library-api
  namespace: library-qa
spec:
  selector:
    app: library-api
  ports:
    - port: 8080
      targetPort: 8080

